function graficof1(Y1, Y2, Y3, titulo, namey)
%CREATEFIGURE(Y1, Y2, Y3)
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 05-Dec-2015 01:14:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(Y1,'DisplayName','Punto Fijo','Marker','x','LineStyle','--',...
    'Color',[0 1 0]);

% Create plot
plot(Y2,'DisplayName','Secante','Marker','diamond','LineStyle','--',...
    'Color',[1 0 1]);

% Create plot
plot(Y3,'DisplayName','Newton Raphson','Marker','square','LineStyle','--',...
    'Color',[0 0 1]);

% Create xlabel
xlabel({'Iteraciones'},'Interpreter','latex');

% Create ylabel
ylabel(namey,'Interpreter','latex');

% Create title
title(titulo,'FontSize',12,'Interpreter','latex');

% Create legend
legend(axes1,'show');

