function errorln_matriz(Y1, Y2)
%CREATEFIGURE(Y1, Y2)
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 27-Dec-2015 18:10:28

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YScale','log');
box(axes1,'on');
hold(axes1,'on');

% Create semilogy
semilogy(Y1,'DisplayName','Gauss-Seidel','Marker','.',...
    'Color',[0.0784313753247261 0.168627455830574 0.549019634723663]);

% Create semilogy
semilogy(Y2,'DisplayName','SOR','Marker','.','Color',[0 1 1]);

% Create xlabel
xlabel('Iteraciones','FontSize',11,'Interpreter','latex');

% Create ylabel
ylabel('Error ln','FontSize',11,'Interpreter','latex');

% Create title
title('Error Ln vs Iteraciones','FontSize',12,'Interpreter','latex');

% Create legend
legend(axes1,'show');

