function GraficoSE(Y1, Y2, titulo, namey)
%CREATEFIGURE(Y1, Y2)
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 02-Dec-2015 12:45:26

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(Y1,'DisplayName','Punto Fijo S.E','Marker','diamond','Color',[0 1 0]);

% Create plot
plot(Y2,'DisplayName','Newton Raphson S.E','Marker','v',...
    'Color',[0 0.447058826684952 0.74117648601532]);

% Create xlabel
xlabel('Iteraciones','Interpreter','latex');

% Create ylabel
ylabel(namey,'Interpreter','latex');

% Create title
title(titulo,'FontWeight','bold','FontSize',12,...
    'Interpreter','latex');

% Create legend
legend(axes1,'show');

